language: swift
osx_image: xcode9.2
before_install:
  - gem install cocoapods
script:
  - xcodebuild clean test -project OpenFoodFactsSDK.xcodeproj -scheme OpenFoodFactsSDK -destination "platform=iOS Simulator,name=iPhone 7,OS=11" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet

